baseURL = "https://de.letb.cl"
languageCode = "en-us"
title = "Decora Eventos"
theme = "resto-hugo"

# Theme specific configuration
[params]
logo = "https://letb.s3-sa-east-1.amazonaws.com/decoraeventos.cl/LOGO_DE.png"
enableDisqus = true # enable / disable comments for blog posts
enableGA = true # enable / disable google analytics
heroText = "Interpretamos tu evento soñado"
footerText = "Cuidaremos cada detalle de tu evento soñado"
facebook = "https://facebook.com/losgnomosambientaciones"
instagram = "https://instagram.com/losgnomoseventos"
